# Generated by Django 4.2 on 2025-08-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company')),
                ('call_us', models.CharField(blank=True, max_length=25, null=True)),
                ('email_us', models.EmailField(blank=True, max_length=254, null=True)),
                ('subtitle', models.TextField(max_length=500)),
                ('fb_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('emails', models.TextField(blank=True, max_length=100, null=True)),
                ('numbers', models.TextField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(max_length=100)),
            ],
        ),
    ]
