# Generated by Django 4.2 on 2025-08-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_brand_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(upload_to="category/", verbose_name="Image"),
        ),
    ]
