# Generated by Django 5.2.5 on 2025-08-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='bcategory/', verbose_name='Image'),
        ),
    ]
