# Generated by Django 5.2.5 on 2025-08-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_alter_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
