# Generated by Django 5.2.5 on 2025-08-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(max_length=10000, verbose_name='Description'),
        ),
    ]
