# Generated by Django 5.2.5 on 2025-08-28 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_alter_product_desc"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="skl",
            new_name="sku",
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.CreateModel(
            name="ProductImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="product_images/")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_image",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ProductImage",
        ),
    ]
